# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maxemilian Grönblom
email: maxemilian@maxemiliang.me
description: > # this means to ignore newlines until "baseurl:"
 a 17 years old webdev student enjoying life and willing to take on challenges
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxemiliang.me" # the base hostname & protocol for your site
twitter_username: maxemiliang
github_username:  maxemiliang

# Build settings
markdown: kramdown
